### ISSUE TITLE
Not initialized properly

### ISSUE THREAD

**Issue by PaulWoitaschek** [kokorin/jebml#1]
When using this library it crashes instantly.

```
java.lang.NullPointerException
	at org.ebml.ProtoType.getInstance(ProtoType.java:51)
	at org.ebml.EBMLReader.readNextElement(EBMLReader.java:113)
```

The solution is to make a call to `MatroskaDocTypes.Void.level` before using this library.
This is really weird to use and the library should handle the initialization itself.

**Comment by kokorin** [comment]
`MatroskaDocTypes.Void` initialized statically. I'm not sure, how calling `MatroskaDocTypes.Void.level` helps you. 
I had to fix simular issue for my other [project](https://github.com/kokorin/Jaffree/blob/master/src/main/java/com/github/kokorin/jaffree/matroska/ExtraDocTypes.java). In short JEBML lacks `Colour` and `EOF` types.
If this won't help, please, provide more details: extra stacktrace, samples or small example which reproduces the problem.

**Comment by PaulWoitaschek** [comment]
I dont fully understand what's happening.
It was introduced in a pull request and without that call I see the above crash.

https://github.com/PaulWoitaschek/Voice/blob/05ec19c1ffd3d6bc0e7ad68dcd4a38e143b1fd21/chapterreader/src/main/java/de/ph1b/audiobook/chapterreader/matroska/ReadAsMatroskaChapters.kt#L24

**Comment by kokorin** [comment]
It seems the issue is in your way of usage of JEBML. Actually you are using raw EBML elements to analyze file, it should be done with a help of MatroskaFile. But, unfortunately, it is able to extract only tracks and frames. 

It would be grate, if you could add this functionality in a pull-request.

**Comment by PaulWoitaschek** [comment]
@p2004a ^
